# Generated by Django 5.2 on 2025-04-21 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('verify_code', models.CharField(max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('is_Doctor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='صاحب عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='Image_news/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('price', models.CharField(max_length=10, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('category', models.ManyToManyField(related_name='post', to='app.category', verbose_name='دسته')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(default=0, max_length=11, verbose_name='موجودی حساب')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('nationality_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('personal_code', models.CharField(blank=True, max_length=5, verbose_name='کد نظام پزشکی')),
                ('date_of_birth', models.CharField(blank=True, max_length=12, verbose_name='تاریخ تولد')),
                ('city', models.CharField(blank=True, max_length=70, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='آدرس')),
                ('photo', models.ImageField(upload_to='face/', verbose_name='عکس')),
                ('nationality_photo', models.ImageField(upload_to='nationality/', verbose_name='عکس کارت ملی')),
                ('personal_photo', models.ImageField(upload_to='personal/', verbose_name='عکس کارت پرسنلی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=70, null=True, verbose_name='شهر')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
                ('plate', models.CharField(max_length=10, verbose_name='پلاک')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('insurance', models.CharField(max_length=100, null=True, verbose_name='بیمه')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رزرو')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
