# Generated by Django 5.2 on 2025-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='صاحب عنوان'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='Image_news/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name=' صاحب عنوان'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name=' عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
