# Generated by Django 5.2 on 2025-04-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_slug_alter_news_desc_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
