# Generated by Django 5.2 on 2025-04-06 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='verify_code',
            field=models.CharField(default=datetime.datetime(2025, 4, 6, 17, 31, 52, 691647, tzinfo=datetime.timezone.utc), max_length=11),
            preserve_default=False,
        ),
    ]
