# Generated by Django 5.2 on 2025-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='قبول شدن'),
        ),
    ]
