# Generated by Django 5.2 on 2025-05-10 15:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان تایید'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='location',
            field=models.CharField(default=datetime.datetime(2025, 5, 10, 15, 17, 47, 77567, tzinfo=datetime.timezone.utc), max_length=200, verbose_name='مکان'),
            preserve_default=False,
        ),
    ]
